### ISSUE TITLE
Window doesn't pop up on command

### ISSUE THREAD

**Issue by serosenstein** [Ja-sonYun/tmux-easy-menu#1]
This seems to be working on my arch box (tmux 3.3a), but not working on my fedora WSL instance on my windows 10 box (again tmux 3.3a).  The menu pops up > click 'n' (network) > click 'p' (ping) > enter IP and window just closes.  Is there a way to debug why the window isn't opening/staying open? I've tried using the exact same tmux.conf from the arch box as well.

**Comment by Ja-sonYun** [comment]
Please try to run follow steps
1. run `tmux-menu popup --cmd "ping %%URL%%" --x 0 --y 0 --w 100 --h 100 --key URL`
2. keep open popup, and open new terminal, and type `echo "URL: google.com\n" > /tmp/tmux-menu.pipe`
3. return to the popup which waiting user input, and type anything and just enter it
4. check that new popup showing the result of ping google.com

Probably the problem is a named pipe.

**Comment by serosenstein** [comment]
thanks for the response.  Your examples helped me find out it needed to add "sudo" for ping in the popup, although my regular user doesn't need to.  Also, I got the "height" is too large error this way and decreased the height and then it started to display.  Thanks!
